apiVersion: apps/v1
kind: Deployment
metadata:
  name: poolmanager
  namespace: default
spec:
  replicas: 2  # Puedes ajustar según la carga
  selector:
    matchLabels:
      app: poolmanager
  template:
    metadata:
      labels:
        app: poolmanager
    spec:
      containers:
      - name: poolmanager
        image: leoduville5/poolmanager:v40
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 1Gi
        env:
        - name: "PORT"
          value: "8080"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poolmanager-secrets
              key: REDIS_PASSWORD
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: poolmanager-secrets
              key: RABBITMQ_PASS
        ports:
        - containerPort: 8080
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 5
      tolerations:
      - key: instance_type
        operator: Equal
        value: spot
        effect: NoSchedule
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         - key: team
      #           operator: In
      #           values:
      #           - devops